### PR TITLE
Update MindManager.download.recipe

### PR DESCRIPTION
**Pull request by bochoven**
Fixed regex (for now)

### CODE REVIEW

**Comment by macmule** [comment]
Bump :)

**Comment by mpanighetti** [comment]
This change is now generating the following error when running any recipe with this recipe present in AutoPkg:

```WARNING: plist error for $autopkgRecipeRepoPath/com.github.autopkg.peshay-recipes/Mindjet/MindManager.download.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "Encountered unexpected character ] on line 26 while looking for close tag" UserInfo={NSDebugDescription=Encountered unexpected character ] on line 26 while looking for close tag, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Malformed data byte group at line 1; invalid hex" UserInfo={NSDebugDescription=Malformed data byte group at line 1; invalid hex}}```

**Comment by roratonet** [comment]
Mpanighetti
Please pull and try again now.

**Comment by mpanighetti** [comment]
That fixed it! Thanks for the quick turnaround.

**Pull request merged**
